FROM python:3.13.10-alpine

# Install dependencies
RUN apk add --no-cache \
    openssh-keygen \
    curl \
    jq && \
    pip install requests

# Copy setup script
COPY beszel-auto-setup.py /setup.py

# Make executable
RUN chmod +x /setup.py

# Set working directory
WORKDIR /app

# Run setup script
CMD ["python3", "/setup.py"]